"use strict";

(() => {
  const core = globalThis.AIScreenerCore;
  if (!core) {
    throw new Error("AIScreenerCore is required before AIScreenerAnalysis");
  }

  const {
    FETCH_SUPPORTED_PROTOCOL,
    FETCH_UPGRADE_PROTOCOL,
    HASH_MODEL_DEFAULT,
    HASH_MODEL_JA,
    clamp,
    normalizeText,
    sigmoid
  } = core;

  const MIN_ANALYZABLE_TEXT_LENGTH = 180;
  const MIN_META_DESCRIPTION_LENGTH = 40;
  const MAX_IDENTICAL_LINE_REPEATS = 1;
  const ARTICLE_CANDIDATE_SELECTORS = [
    "article",
    "main",
    "[role='main']",
    "[itemprop='articleBody']",
    ".post",
    ".entry-content",
    ".article-body"
  ];
  const NON_CONTENT_NODE_SELECTORS = [
    "script,style,noscript,svg,canvas,iframe,form,template",
    "nav,footer,header,aside",
    "[hidden],[aria-hidden='true'],input[type='hidden']",
    "[style*='display:none'],[style*='display: none'],[style*='visibility:hidden'],[style*='visibility: hidden']",
    "[class*='dummy'],[class*='placeholder'],[class*='skeleton'],[class*='loading'],[class*='pager'],[class*='controller'],[class*='dotList'],[class*='dots']"
  ];
  const META_DESCRIPTION_SELECTORS = [
    "meta[name='description']",
    "meta[property='og:description']",
    "meta[name='twitter:description']"
  ];
  const EN_STOPWORDS = new Set([
    "a", "an", "and", "are", "as", "at", "be", "by", "for", "from", "has", "have",
    "in", "is", "it", "its", "of", "on", "or", "that", "the", "to", "was", "were",
    "will", "with", "this", "these", "those", "you", "your", "we", "our", "can",
    "not", "if", "then", "than", "about", "into", "which", "what", "when", "where"
  ]);
  const AI_DISCLOSURE_PATTERNS = [
    /\b(?:story|text|article|post|content|novel|book|poem|image|art|illustration|message|messages|carol|carols|costume|costumes|recipe|recipes)\s+(?:written|generated|created|drawn|illustrated|made|produced)\s+by\s+(?:a |an )?(?:ai|neural network|neural net|language model|llm|chatbot|gpt(?:-\d+)?|chatgpt|claude|gemini|dall-e|stable diffusion|midjourney)\b/i,
    /\b(?:written|generated|created|drawn|illustrated|made|produced)\s+by\s+(?:a |an )?(?:ai|neural network|neural net|language model|llm|chatbot|gpt(?:-\d+)?|chatgpt|claude|gemini|dall-e|stable diffusion|midjourney)\b/i,
    /\bwritten with (?:gpt|ai)\b/i,
    /\bcreated with (?:gpt|ai)\b/i,
    /\bgenerated with (?:ai|gpt|a neural network|neural network|neural net)\b/i,
    /\bthis (?:story|text|article|post|content|novel|book|poem|image|art|illustration) was (?:generated|written|created)\b/i,
    /\babove text is machine-generated\b/i,
    /\bfree ai-generated (?:novel|story|book)\b/i,
    /\bai novel writing technology\b/i,
    /ai生成/i,
    /aiで生成/i,
    /生成ai/i,
    /aiが作成/i,
    /aiで作成/i
  ];
  const GENERATED_CONTENT_CUE_PATTERNS = [
    /\bai-generated\b/i,
    /\bgenerated by ai\b/i,
    /\bmachine-generated\b/i,
    /\bmachine generated\b/i,
    /\b(?:neural network|neural net|char-rnn|chatbot|language model|llm|chatgpt|gpt(?:-\d+)?|claude|gemini|dall-e|stable diffusion|midjourney).{0,60}\b(?:generate|generated|generates|creating|created|creates|write|written|wrote|draw|drawn|drew|illustrate|illustrated|produce|produced|invented)\b/i,
    /\b(?:generate|generated|generates|creating|created|creates|write|written|wrote|draw|drawn|drew|illustrate|illustrated|produce|produced|invented)\b.{0,60}\b(?:neural network|neural net|char-rnn|chatbot|language model|llm|chatgpt|gpt(?:-\d+)?|claude|gemini|dall-e|stable diffusion|midjourney)\b/i,
    /\b(?:ai|neural network|neural net|char-rnn|chatbot|language model|llm|chatgpt|gpt(?:-\d+)?|claude|gemini|dall-e|stable diffusion|midjourney)(?: |-)?generated\b/i,
    /ai生成/i,
    /aiで生成/i,
    /生成ai/i
  ];
  const SUMMARY_DISCLAIMER_PATTERNS = [
    /\bread ai-generated summary\b/i,
    /\bai-generated summary\b/i,
    /\bsummaries were generated by .*? ai\b/i,
    /\bgenerative ai is experimental\b/i
  ];
  const AI_ROUTE_HINT_PATTERNS = [
    /\/story(?:\/|$)/i,
    /\/stories(?:\/|$)/i,
    /\/novel(?:\/|$)/i,
    /\/novels(?:\/|$)/i,
    /\/fiction(?:\/|$)/i,
    /\/generated(?:\/|$)/i,
    /\/prompt(?:\/|$)/i,
    /\bai (?:book|novel|story|fiction)\b/i,
    /\bmachine-generated\b/i
  ];
  const OFFICIAL_GUARD_PATTERNS = [
    /(^|[/.])docs[/.]/i,
    /\/docs?(?:\/|$)/i,
    /\/support(?:\/|$)/i,
    /\/help(?:\/|$)/i,
    /\/guide(?:s)?(?:\/|$)/i,
    /\/cookbook(?:\/|$)/i,
    /\/reference(?:\/|$)/i,
    /\/api(?:\/|$)/i,
    /\/pricing(?:\/|$)/i,
    /\/product(?:s)?(?:\/|$)/i,
    /\/feature(?:\/|$)/i,
    /\/spec(?:s)?(?:\/|$)/i,
    /\/shop(?:\/|$)/i,
    /\/store(?:\/|$)/i,
    /apple\.com/i,
    /google\./i,
    /anthropic\.com/i,
    /openai\.com/i,
    /vercel\.com/i,
    /pokemon\.co\.jp/i,
    /pokemoncenter-online\.com/i
  ];

  function resolveFetchUrl(rawUrl) {
    let parsed = null;
    try {
      parsed = new URL(rawUrl);
    } catch (_error) {
      return "";
    }

    if (parsed.protocol === FETCH_SUPPORTED_PROTOCOL) {
      return parsed.href;
    }
    if (parsed.protocol === FETCH_UPGRADE_PROTOCOL) {
      parsed.protocol = FETCH_SUPPORTED_PROTOCOL;
      return parsed.href;
    }
    return "";
  }

  function buildPayloadFromSnippet(result) {
    const text = normalizeText(`${result.title || ""}\n${result.snippet || ""}`);
    const headingsText = result.title || "";
    const metrics = buildTextMetrics(text, headingsText, 0, "snippet", result.url);
    return {
      text,
      headingsText,
      metaDescription: "",
      externalLinkCount: 0,
      source: "snippet",
      url: result.url,
      qualityScore: metrics.qualityScore,
      metrics
    };
  }

  function buildPayloadFromMetaDescription(result, payload) {
    const description = normalizeText(payload.metaDescription || "");
    if (description.length < MIN_META_DESCRIPTION_LENGTH) {
      return null;
    }

    const heading = normalizeText(payload.headingsText || result.title || "");
    const text = heading && !description.startsWith(heading)
      ? normalizeText(`${heading}\n${description}`)
      : description;
    const externalLinkCount = Number(payload.externalLinkCount) || 0;
    const metrics = buildTextMetrics(text, heading, externalLinkCount, "meta", payload.url || result.url);

    return {
      text,
      headingsText: heading,
      metaDescription: description,
      externalLinkCount,
      source: "meta",
      url: payload.url || result.url,
      qualityScore: metrics.qualityScore,
      metrics
    };
  }

  function chooseBestPayload(fetchedPayload, metaPayload, snippetPayload) {
    const candidates = [fetchedPayload, metaPayload, snippetPayload].filter((payload) => payload && payload.text);
    if (candidates.length === 0) {
      return snippetPayload;
    }

    if (shouldPreferMetaPayload(fetchedPayload, metaPayload)) {
      return finalizeSelectedPayload(metaPayload, fetchedPayload, metaPayload);
    }

    if (
      fetchedPayload &&
      fetchedPayload.text &&
      fetchedPayload.text.length >= MIN_ANALYZABLE_TEXT_LENGTH &&
      Number(fetchedPayload.qualityScore) >= 0.55
    ) {
      return finalizeSelectedPayload(fetchedPayload, fetchedPayload, metaPayload);
    }

    candidates.sort((left, right) => {
      const qualityDiff = (Number(right.qualityScore) || 0) - (Number(left.qualityScore) || 0);
      if (Math.abs(qualityDiff) > 0.0001) {
        return qualityDiff;
      }
      return (right.text || "").length - (left.text || "").length;
    });
    return finalizeSelectedPayload(candidates[0], fetchedPayload, metaPayload);
  }

  function finalizeSelectedPayload(selectedPayload, bodyPayload, metaPayload) {
    if (!selectedPayload) {
      return bodyPayload || metaPayload;
    }

    const metrics = { ...(selectedPayload.metrics || {}) };
    const bodyQuality = Number(bodyPayload?.qualityScore) || 0;
    const metaQuality = Number(metaPayload?.qualityScore) || 0;
    const pageUrl = selectedPayload.url || bodyPayload?.url || metaPayload?.url || "";

    metrics.metaBodyGap = clamp(metaQuality - bodyQuality, -1, 1);
    metrics.shellPageRatio = Math.max(
      Number(metrics.shellPageRatio) || 0,
      computeShellPageRatio(bodyPayload?.metrics || metrics)
    );
    metrics.templateFootprint = Math.max(
      Number(metrics.templateFootprint) || 0,
      computeTemplateFootprint(bodyPayload?.metrics || metrics)
    );
    metrics.explicitAiDisclosure = hasExplicitAiDisclosure(
      selectedPayload.headingsText,
      selectedPayload.metaDescription,
      selectedPayload.text,
      pageUrl
    ) ? 1 : 0;
    metrics.contentGenerationCue = hasGeneratedContentCue(
      selectedPayload.headingsText,
      selectedPayload.metaDescription,
      selectedPayload.text,
      pageUrl
    ) ? 1 : 0;
    metrics.aiRouteHint = hasAiRouteHint(pageUrl, selectedPayload.headingsText) ? 1 : 0;
    metrics.officialGuard = (
      looksOfficialGuarded(pageUrl) &&
      metrics.explicitAiDisclosure < 0.5
    ) ? 1 : 0;
    metrics.titleBodyConsistency = textOverlapScore(selectedPayload.headingsText, (selectedPayload.text || "").slice(0, 1200));
    metrics.metaBodyConsistency = (
      metaPayload && metaPayload.metaDescription && bodyPayload?.text
        ? textOverlapScore(metaPayload.metaDescription, String(bodyPayload.text || "").slice(0, 1200))
        : 0
    );
    const cueGap = Math.abs(
      (Number(metaPayload?.metrics?.contentGenerationCue) || 0) -
      (Number(bodyPayload?.metrics?.contentGenerationCue) || 0)
    );
    metrics.sourceDisagreement = clamp(
      0.55 * (1 - (Number(metrics.metaBodyConsistency) || 0)) +
      0.25 * Math.abs(Number(metrics.metaBodyGap) || 0) +
      0.20 * cueGap,
      0,
      1
    );
    metrics.disclaimerDensity = Math.max(
      Number(metrics.disclaimerDensity) || 0,
      computeDisclaimerDensity(selectedPayload.headingsText, selectedPayload.text, selectedPayload.metaDescription)
    );
    metrics.shortShellGuard = Math.max(
      Number(metrics.shortShellGuard) || 0,
      (
        (Number(metrics.shellPageRatio) || 0) >= 0.42 &&
        (Number(metrics.textLength) || 0) <= 640 &&
        (Number(metrics.sentenceCount) || 0) <= 6
      ) ? 1 : 0
    );

    return {
      ...selectedPayload,
      url: pageUrl,
      metrics
    };
  }

  function shouldPreferMetaPayload(fetchedPayload, metaPayload) {
    if (!metaPayload || !metaPayload.text) {
      return false;
    }
    if (!fetchedPayload || !fetchedPayload.text) {
      return true;
    }

    const metrics = fetchedPayload.metrics || {};
    const textLength = Number(metrics.textLength) || fetchedPayload.text.length;
    const sentenceCount = Number(metrics.sentenceCount) || 0;
    const shortLineRatio = Number(metrics.shortLineRatio) || 0;
    const punctuationRatio = Number(metrics.punctuationCharRatio) || 0;
    const headingRatio = Number(metrics.headingBodyRatio) || 0;
    const templateFootprint = Number(metrics.templateFootprint) || 0;
    const disclaimerScore = Number(metrics.disclaimerDensity) || 0;
    const metaMargin = (Number(metaPayload.qualityScore) || 0) - (Number(fetchedPayload.qualityScore) || 0);
    const bodyGenerationCue = Number(metrics.contentGenerationCue) || 0;
    const metaGenerationCue = Number(metaPayload.metrics?.contentGenerationCue) || 0;
    const metaHasExplicitAiCue = Number(metaPayload.metrics?.explicitAiDisclosure) >= 0.5;
    const bodyConsistency = Number(metrics.titleBodyConsistency) || 0;
    const pageUrl = metaPayload.url || fetchedPayload.url || "";
    const officialGuard = looksOfficialGuarded(pageUrl);

    const bodyLooksLikeUi = (
      shortLineRatio >= 0.48 &&
      sentenceCount <= 4 &&
      punctuationRatio <= 0.025 &&
      textLength <= 420
    );
    const bodyIsTitleHeavy = headingRatio >= 0.28 && textLength <= 480;
    const bodyLowTrust = (
      bodyLooksLikeUi ||
      bodyIsTitleHeavy ||
      templateFootprint >= 0.52 ||
      (disclaimerScore >= 0.18 && bodyConsistency < 0.35)
    );
    return (
      (bodyLowTrust && metaMargin >= -0.08) ||
      (metaHasExplicitAiCue && (bodyLowTrust || Number(fetchedPayload.qualityScore) < 0.68)) ||
      (
        !officialGuard &&
        metaGenerationCue > bodyGenerationCue &&
        metaMargin >= -0.16 &&
        (bodyLowTrust || bodyConsistency < 0.44)
      )
    );
  }

  function analyzePayload(payload) {
    const selectedModel = selectHashModel(payload.text || payload.headingsText || "");
    const baseHashScore = computeHashScore(payload.text || "", selectedModel);
    const score = computeFinalScore(payload, selectedModel, baseHashScore);
    const judge = toJudge(score, selectedModel);

    return {
      score,
      judge,
      displayScore: score.toFixed(2)
    };
  }

  function selectHashModel(text) {
    if (HASH_MODEL_JA && isLikelyJapaneseText(text)) {
      return HASH_MODEL_JA;
    }
    return HASH_MODEL_DEFAULT;
  }

  function isLikelyJapaneseText(text) {
    const sample = String(text || "").slice(0, 2400);
    if (!sample) {
      return false;
    }

    const matches = sample.match(/[\u3040-\u30ff\u4e00-\u9fff]/g);
    const jpCount = matches ? matches.length : 0;
    if (jpCount >= 40) {
      return true;
    }
    return jpCount >= 8 && jpCount / Math.max(1, sample.length) >= 0.03;
  }

  function computeHashScore(text, model) {
    const activeModel = model || HASH_MODEL_DEFAULT;
    const normalized = normalizeHashText(text);
    if (normalized.length < 3) {
      return 0.5;
    }

    const limit = Math.min(normalized.length, activeModel.max_chars);
    let logit = activeModel.prior_logit;

    for (let i = 0; i < limit - 2; i += 1) {
      const bin = hashTrigram(normalized, i, activeModel.dim);
      logit += activeModel.delta[bin] || 0;
    }

    return sigmoid(logit);
  }

  function computeFinalScore(payload, model, baseHashScore) {
    const calibration = model && model.calibration;
    const metrics = payload.metrics || buildTextMetrics(
      payload.text || "",
      payload.headingsText || "",
      Number(payload.externalLinkCount) || 0,
      payload.source || "body",
      payload.url || ""
    );

    if (!calibration) {
      return blendScoreWithQuality(baseHashScore, metrics.qualityScore, metrics);
    }

    const vector = createFeatureVector(baseHashScore, metrics);
    let logit = Number(calibration.bias) || 0;
    for (let index = 0; index < vector.length; index += 1) {
      const mean = Number(calibration.means[index]) || 0;
      const scale = Math.abs(Number(calibration.scales[index]) || 1) > 1e-9
        ? Number(calibration.scales[index]) || 1
        : 1;
      const weight = Number(calibration.weights[index]) || 0;
      logit += ((vector[index] - mean) / scale) * weight;
    }

    return blendScoreWithQuality(sigmoid(logit), metrics.qualityScore, metrics);
  }

  function blendScoreWithQuality(score, qualityScore, metrics) {
    const sourcePenalty = 0.10 * Number(metrics?.sourceSnippet || 0) + 0.04 * Number(metrics?.sourceMeta || 0);
    const confidence = clamp((Number(qualityScore) || 0) - sourcePenalty, 0, 1);
    const blend = 0.25 + 0.75 * confidence;
    return clamp(0.5 + (Number(score) - 0.5) * blend, 0, 1);
  }

  function createFeatureVector(baseHashScore, metrics) {
    return [
      clamp(baseHashScore, 0, 1),
      Math.log1p(Math.max(0, Number(metrics.textLength) || 0)),
      Number(metrics.sentenceCount) || 0,
      Number(metrics.avgSentenceLength) || 0,
      Number(metrics.sentenceLengthStd) || 0,
      Number(metrics.lineCount) || 0,
      Number(metrics.shortLineRatio) || 0,
      Number(metrics.repeatLineRatio) || 0,
      Number(metrics.uniqueLineRatio) || 0,
      Number(metrics.bulletLineRatio) || 0,
      Number(metrics.headingBodyRatio) || 0,
      Number(metrics.numericCharRatio) || 0,
      Number(metrics.dateLikeRatio) || 0,
      Number(metrics.currencyLikeRatio) || 0,
      Number(metrics.productCodeRatio) || 0,
      Number(metrics.externalLinkDensity) || 0,
      Number(metrics.punctuationCharRatio) || 0,
      Number(metrics.symbolCharRatio) || 0,
      Number(metrics.qualityScore) || 0,
      Number(metrics.explicitAiDisclosure) || 0,
      Number(metrics.aiRouteHint) || 0,
      Number(metrics.shellPageRatio) || 0,
      Number(metrics.officialGuard) || 0,
      Number(metrics.metaBodyGap) || 0,
      Number(metrics.contentGenerationCue) || 0,
      Number(metrics.templateFootprint) || 0,
      Number(metrics.titleBodyConsistency) || 0,
      Number(metrics.metaBodyConsistency) || 0,
      Number(metrics.sourceDisagreement) || 0,
      Number(metrics.disclaimerDensity) || 0,
      Number(metrics.shortShellGuard) || 0,
      Number(metrics.sourceBody) || 0,
      Number(metrics.sourceMeta) || 0,
      Number(metrics.sourceSnippet) || 0,
      Number(metrics.jpCharRatio) || 0,
      Number(metrics.hiraganaRatio) || 0,
      Number(metrics.katakanaRatio) || 0,
      Number(metrics.kanjiRatio) || 0,
      Number(metrics.latinRatio) || 0,
      Number(metrics.stopwordRatio) || 0,
      Number(metrics.vocabRichness) || 0
    ];
  }

  function normalizeHashText(value) {
    return normalizeText(value || "")
      .toLowerCase()
      .replace(/\u00a0/g, " ");
  }

  function hashTrigram(text, start, dim) {
    let h = 2166136261;
    for (let i = 0; i < 3; i += 1) {
      h ^= text.charCodeAt(start + i);
      h = Math.imul(h, 16777619) >>> 0;
    }
    return h % dim;
  }

  function toJudge(score, model) {
    const activeModel = model || HASH_MODEL_DEFAULT;
    if (score < activeModel.thresholds.human_max) {
      return "Human";
    }
    if (score < activeModel.thresholds.ai_min) {
      return "Unknown";
    }
    return "AI";
  }

  function extractFromHtml(html, url) {
    try {
      const sanitized = sanitizeFetchedHtml(html);
      const doc = new DOMParser().parseFromString(sanitized, "text/html");
      return extractFromDocument(doc, url, "body");
    } catch (_error) {
      return createEmptyPayload("body");
    }
  }

  function sanitizeFetchedHtml(html) {
    return String(html || "").replace(/<base\b[^>]*>/gi, "");
  }

  function createEmptyPayload(source) {
    return {
      text: "",
      headingsText: "",
      metaDescription: "",
      externalLinkCount: 0,
      source,
      url: "",
      qualityScore: 0,
      metrics: buildTextMetrics("", "", 0, source || "body", "")
    };
  }

  function extractFromDocument(doc, url, source = "document") {
    const body = doc.body;
    if (!body) {
      return createEmptyPayload(source);
    }

    const clone = body.cloneNode(true);
    pruneNonContentNodes(clone);

    const mainElement = pickMainTextElement(clone);
    const text = postProcessExtractedText(mainElement.innerText || clone.innerText || "");
    const headingsText = Array.from(mainElement.querySelectorAll("h1,h2,h3"))
      .map((node) => normalizeText(node.innerText || ""))
      .filter(Boolean)
      .join(" ");
    const metaDescription = readMetaDescription(doc);
    const externalLinkCount = countExternalLinks(mainElement, url);
    const payloadSource = source === "fetched" ? "body" : source;
    const metrics = buildTextMetrics(text, headingsText, externalLinkCount, payloadSource, url);

    return {
      text,
      headingsText,
      metaDescription,
      externalLinkCount,
      source: payloadSource,
      url,
      qualityScore: metrics.qualityScore,
      metrics
    };
  }

  function pickMainTextElement(root) {
    let best = null;
    let bestLength = 0;

    for (const selector of ARTICLE_CANDIDATE_SELECTORS) {
      for (const element of root.querySelectorAll(selector)) {
        const length = normalizeText(element.innerText || "").length;
        if (length > bestLength) {
          best = element;
          bestLength = length;
        }
      }
    }

    return best || root;
  }

  function pruneNonContentNodes(root) {
    for (const selector of NON_CONTENT_NODE_SELECTORS) {
      removeNodesBySelector(root, selector);
    }
  }

  function removeNodesBySelector(root, selector) {
    for (const node of root.querySelectorAll(selector)) {
      node.remove();
    }
  }

  function postProcessExtractedText(value) {
    const seen = new Map();
    const lines = String(value || "")
      .replace(/\u3000+/g, " ")
      .split(/\n+/)
      .map((line) => normalizeText(line))
      .filter(Boolean)
      .filter((line) => !isUiOnlyLine(line));

    const kept = [];
    for (const line of lines) {
      const count = seen.get(line) || 0;
      if (count >= MAX_IDENTICAL_LINE_REPEATS) {
        continue;
      }
      seen.set(line, count + 1);
      kept.push(line);
    }

    return kept.join("\n");
  }

  function isUiOnlyLine(line) {
    const value = String(line || "").trim();
    if (!value) {
      return true;
    }
    if (/^(前へ|次へ|prev|next|\d+)$/i.test(value)) {
      return true;
    }
    if (/^[\p{P}\p{S}ー・]+$/u.test(value)) {
      return true;
    }
    if (/^[A-Z0-9\-_.]{1,6}$/u.test(value)) {
      return true;
    }
    return value.length < 4 && !/[。！？!?.]/.test(value);
  }

  function buildTextMetrics(text, headingsText = "", externalLinkCount = 0, source = "body", pageUrl = "", metaQualityScore = 0, bodyQualityScore = 0) {
    const normalizedText = normalizeText(text || "");
    const normalizedHeading = normalizeText(headingsText || "");
    const lines = normalizedText
      .split(/\n+/)
      .map((line) => normalizeText(line))
      .filter(Boolean)
      .filter((line) => !isUiOnlyLine(line));
    const uniqueLineRatio = lines.length === 0 ? 0 : new Set(lines).size / lines.length;
    const repeatLineRatio = lines.length === 0 ? 0 : 1 - uniqueLineRatio;
    const shortLineCount = lines.filter((line) => line.length <= 24).length;
    const bulletLineCount = lines.filter((line) => /^(?:[-*•・]|[0-9]{1,2}[.)]|[0-9]{1,2}[:：])/.test(line)).length;
    const sentences = splitSentences(normalizedText);
    const sentenceLengths = sentences.map((sentence) => sentence.length);
    const tokens = tokenizeWords(normalizedText);
    const stopwordCount = tokens.filter((token) => EN_STOPWORDS.has(token)).length;

    const metrics = {
      textLength: normalizedText.length,
      sentenceCount: sentences.length,
      avgSentenceLength: average(sentenceLengths),
      sentenceLengthStd: standardDeviation(sentenceLengths),
      lineCount: lines.length,
      shortLineRatio: ratio(shortLineCount, lines.length),
      repeatLineRatio,
      uniqueLineRatio,
      bulletLineRatio: ratio(bulletLineCount, lines.length),
      headingBodyRatio: Math.min(2, normalizedHeading.length / Math.max(1, normalizedText.length)),
      titleBodyConsistency: textOverlapScore(normalizedHeading, normalizedText.slice(0, 1200)),
      metaBodyConsistency: 0,
      sourceDisagreement: 0,
      numericCharRatio: matchRatio(normalizedText, /\d/g),
      dateLikeRatio: ratio((normalizedText.match(/(?:\d{4}[/-]\d{1,2}[/-]\d{1,2}|\d{1,2}月\d{1,2}日|\d{1,2}\/\d{1,2})/g) || []).length, Math.max(1, sentences.length)),
      currencyLikeRatio: ratio((normalizedText.match(/(?:¥|\$|€|£|円|USD|JPY)/g) || []).length, Math.max(1, sentences.length)),
      productCodeRatio: ratio((normalizedText.match(/\b[A-Z0-9][A-Z0-9._-]{3,}\b/g) || []).length, Math.max(1, tokens.length)),
      externalLinkDensity: ratio(externalLinkCount, Math.max(1, lines.length)),
      punctuationCharRatio: matchRatio(normalizedText, /[。．！？!?.,;:：；、]/g),
      symbolCharRatio: matchRatio(normalizedText, /[\-–—_/\\|+=*&^%$#@~`"'(){}\[\]<>]/g),
      sourceBody: source === "body" ? 1 : 0,
      sourceMeta: source === "meta" ? 1 : 0,
      sourceSnippet: source === "snippet" ? 1 : 0,
      jpCharRatio: matchRatio(normalizedText, /[\u3040-\u30ff\u4e00-\u9fff]/g),
      hiraganaRatio: matchRatio(normalizedText, /[\u3040-\u309f]/g),
      katakanaRatio: matchRatio(normalizedText, /[\u30a0-\u30ff]/g),
      kanjiRatio: matchRatio(normalizedText, /[\u4e00-\u9fff]/g),
      latinRatio: matchRatio(normalizedText, /[A-Za-z]/g),
      stopwordRatio: isLikelyJapaneseText(normalizedText) ? 0 : ratio(stopwordCount, Math.max(1, tokens.length)),
      vocabRichness: ratio(new Set(tokens).size, Math.max(1, tokens.length))
    };

    metrics.qualityScore = computeQualityScore(metrics, source);
    metrics.explicitAiDisclosure = hasExplicitAiDisclosure(normalizedHeading, normalizedText) ? 1 : 0;
    metrics.contentGenerationCue = hasGeneratedContentCue(normalizedHeading, normalizedText) ? 1 : 0;
    metrics.aiRouteHint = hasAiRouteHint(pageUrl, normalizedHeading) ? 1 : 0;
    metrics.shellPageRatio = computeShellPageRatio(metrics);
    metrics.templateFootprint = computeTemplateFootprint(metrics);
    metrics.disclaimerDensity = computeDisclaimerDensity(normalizedHeading, normalizedText);
    metrics.shortShellGuard = (
      metrics.shellPageRatio >= 0.42 &&
      metrics.textLength <= 640 &&
      metrics.sentenceCount <= 6
    ) ? 1 : 0;
    metrics.officialGuard = (
      looksOfficialGuarded(pageUrl) &&
      metrics.explicitAiDisclosure < 0.5
    ) ? 1 : 0;
    metrics.metaBodyGap = clamp(Number(metaQualityScore) - Number(bodyQualityScore), -1, 1);
    return metrics;
  }

  function computeQualityScore(metrics, source) {
    const sentenceSignal = metrics.sentenceCount >= 2 ? 1 : metrics.sentenceCount / 2;
    const contentSignal = Math.min(1, (Number(metrics.textLength) || 0) / 900);
    const sourceBonus = source === "body" ? 0.15 : (source === "meta" ? 0.05 : -0.05);
    const quality = (
      0.28 * contentSignal +
      0.18 * sentenceSignal +
      0.18 * (Number(metrics.uniqueLineRatio) || 0) +
      0.14 * (1 - (Number(metrics.shortLineRatio) || 0)) +
      0.12 * (1 - (Number(metrics.repeatLineRatio) || 0)) +
      0.10 * Math.max(0, 1 - (Number(metrics.bulletLineRatio) || 0)) +
      sourceBonus
    );
    return clamp(quality, 0, 1);
  }

  function splitSentences(text) {
    const normalized = normalizeText(text || "");
    if (!normalized) {
      return [];
    }
    const parts = normalized
      .split(/(?:[。！？!?]+|\.\s+)/)
      .map((value) => normalizeText(value))
      .filter(Boolean);
    return parts.length > 0 ? parts : [normalized];
  }

  function tokenizeWords(text) {
    return Array.from(String(text || "").matchAll(/[A-Za-z']+/g), (match) => String(match[0] || "").toLowerCase());
  }

  function matchRatio(text, pattern) {
    if (!text) {
      return 0;
    }
    const matches = text.match(pattern);
    return ratio(matches ? matches.length : 0, text.length);
  }

  function average(values) {
    if (!Array.isArray(values) || values.length === 0) {
      return 0;
    }
    return values.reduce((sum, value) => sum + (Number(value) || 0), 0) / values.length;
  }

  function hasExplicitAiDisclosure(...values) {
    const combined = values
      .map((value) => normalizeText(value || ""))
      .filter(Boolean)
      .join("\n");
    if (!combined) {
      return false;
    }
    const sanitized = stripSummaryDisclaimerLines(combined);
    if (!sanitized) {
      return false;
    }
    return AI_DISCLOSURE_PATTERNS.some((pattern) => pattern.test(sanitized));
  }

  function hasGeneratedContentCue(...values) {
    const combined = values
      .map((value) => normalizeText(value || ""))
      .filter(Boolean)
      .join("\n");
    if (!combined) {
      return false;
    }
    return GENERATED_CONTENT_CUE_PATTERNS.some((pattern) => pattern.test(combined));
  }

  function countPatternOccurrences(patterns, text) {
    const value = normalizeText(text || "");
    if (!value) {
      return 0;
    }
    return patterns.reduce((sum, pattern) => {
      const matches = value.match(pattern);
      return sum + (matches ? matches.length : 0);
    }, 0);
  }

  function stripSummaryDisclaimerLines(text) {
    return String(text || "")
      .split(/\n+/)
      .map((line) => normalizeText(line))
      .filter(Boolean)
      .filter((line) => !SUMMARY_DISCLAIMER_PATTERNS.some((pattern) => pattern.test(line)))
      .join("\n");
  }

  function computeDisclaimerDensity(...values) {
    const combined = values
      .map((value) => normalizeText(value || ""))
      .filter(Boolean)
      .join("\n");
    if (!combined) {
      return 0;
    }
    return clamp(countPatternOccurrences(SUMMARY_DISCLAIMER_PATTERNS, combined) / Math.max(1, splitSentences(combined).length), 0, 1);
  }

  function similarityUnits(text) {
    const normalized = normalizeText(text || "").toLowerCase();
    if (!normalized) {
      return new Set();
    }
    const units = new Set(tokenizeWords(normalized));
    const compact = normalized.replace(/[^0-9a-z\u3040-\u30ff\u4e00-\u9fff]+/g, "");
    if (compact.length >= 2) {
      const limit = Math.min(compact.length - 1, 96);
      for (let index = 0; index < limit; index += 1) {
        units.add(compact.slice(index, index + 2));
      }
    } else if (compact) {
      units.add(compact);
    }
    return units;
  }

  function textOverlapScore(left, right) {
    const leftUnits = similarityUnits(left);
    const rightUnits = similarityUnits(right);
    if (leftUnits.size === 0 || rightUnits.size === 0) {
      return 0;
    }
    let matches = 0;
    for (const unit of leftUnits) {
      if (rightUnits.has(unit)) {
        matches += 1;
      }
    }
    return matches / Math.max(1, Math.min(leftUnits.size, rightUnits.size));
  }

  function hasAiRouteHint(pageUrl, headingsText = "") {
    const combined = [normalizeText(pageUrl || ""), normalizeText(headingsText || "")]
      .filter(Boolean)
      .join("\n");
    if (!combined) {
      return false;
    }
    return AI_ROUTE_HINT_PATTERNS.some((pattern) => pattern.test(combined));
  }

  function looksOfficialGuarded(pageUrl) {
    const value = normalizeText(pageUrl || "");
    if (!value) {
      return false;
    }
    return OFFICIAL_GUARD_PATTERNS.some((pattern) => pattern.test(value));
  }

  function computeShellPageRatio(metrics) {
    const shortLineRatio = Number(metrics.shortLineRatio) || 0;
    const repeatLineRatio = Number(metrics.repeatLineRatio) || 0;
    const headingRatio = Number(metrics.headingBodyRatio) || 0;
    const sentenceCount = Number(metrics.sentenceCount) || 0;
    const punctuationRatio = Number(metrics.punctuationCharRatio) || 0;
    const textLength = Number(metrics.textLength) || 0;

    const sentencePenalty = clamp((4 - Math.min(sentenceCount, 4)) / 4, 0, 1);
    const punctuationPenalty = clamp((0.03 - Math.min(punctuationRatio, 0.03)) / 0.03, 0, 1);
    const lengthPenalty = clamp((480 - Math.min(textLength, 480)) / 480, 0, 1);
    return clamp(
      0.28 * shortLineRatio +
      0.24 * repeatLineRatio +
      0.22 * clamp(headingRatio / 0.4, 0, 1) +
      0.14 * sentencePenalty +
      0.07 * punctuationPenalty +
      0.05 * lengthPenalty,
      0,
      1
    );
  }

  function computeTemplateFootprint(metrics) {
    return clamp(
      0.38 * (Number(metrics.repeatLineRatio) || 0) +
      0.24 * (Number(metrics.shortLineRatio) || 0) +
      0.18 * (Number(metrics.bulletLineRatio) || 0) +
      0.20 * clamp((Number(metrics.headingBodyRatio) || 0) / 0.45, 0, 1),
      0,
      1
    );
  }

  function standardDeviation(values) {
    if (!Array.isArray(values) || values.length < 2) {
      return 0;
    }
    const mean = average(values);
    const variance = values.reduce((sum, value) => {
      const delta = (Number(value) || 0) - mean;
      return sum + delta * delta;
    }, 0) / values.length;
    return Math.sqrt(variance);
  }

  function ratio(part, whole) {
    const denominator = Number(whole) || 0;
    if (denominator <= 0) {
      return 0;
    }
    return (Number(part) || 0) / denominator;
  }

  function readMetaDescription(doc) {
    for (const selector of META_DESCRIPTION_SELECTORS) {
      const content = normalizeText(doc.querySelector(selector)?.getAttribute("content") || "");
      if (content) {
        return content;
      }
    }

    return "";
  }

  function countExternalLinks(root, pageUrl) {
    let host = "";
    try {
      host = new URL(pageUrl).host;
    } catch (_error) {
      host = "";
    }

    let count = 0;
    for (const anchor of root.querySelectorAll("a[href]")) {
      const href = anchor.getAttribute("href");
      if (!href || !/^https?:\/\//i.test(href)) {
        continue;
      }

      try {
        const linked = new URL(href);
        if (!host || linked.host !== host) {
          count += 1;
        }
      } catch (_error) {
        continue;
      }
    }

    return count;
  }

  globalThis.AIScreenerAnalysis = {
    resolveFetchUrl,
    buildPayloadFromSnippet,
    buildPayloadFromMetaDescription,
    chooseBestPayload,
    createEmptyPayload,
    extractFromHtml,
    analyzePayload
  };
})();
