"use strict";

(() => {
  const SETTINGS_KEY = "settings";
  const CACHE_PREFIX = "cache:";
  const CACHE_VERSION = 11;
  const DEFAULT_CACHE_TTL_HOURS = 24 * 7;
  const SEARCH_SCAN_DEBOUNCE_MS = 250;
  const ANALYSIS_CONCURRENCY = 2;
  const FETCH_SUPPORTED_PROTOCOL = "https:";
  const FETCH_UPGRADE_PROTOCOL = "http:";
  const MIN_ANALYZABLE_TEXT_LENGTH = 180;
  const MIN_META_DESCRIPTION_LENGTH = 40;
  const MAX_IDENTICAL_LINE_REPEATS = 1;
  const RESULT_H3_SELECTOR = "#search a h3";
  const RESULT_CONTAINER_SELECTOR = "div.MjjYud, div.g";
  const RESULT_SNIPPET_SELECTOR = ".VwiC3b, .IsZvec, .s3v9rd";
  const INLINE_CARD_BREAKPOINT = 1180;
  const CARD_CLASS = "ai-screener-card";
  const CARD_STATE_LOADING = "loading";
  const CARD_STATE_DONE = "done";
  const CARD_STATE_ERROR = "error";
  const CARD_TONE_CLASSES = [
    "ai-screener-card-ai",
    "ai-screener-card-human",
    "ai-screener-card-unknown",
    "ai-screener-card-checking",
    "ai-screener-card-error"
  ];
  const ARTICLE_CANDIDATE_SELECTORS = [
    "article",
    "main",
    "[role='main']",
    "[itemprop='articleBody']",
    ".post",
    ".entry-content",
    ".article-body"
  ];
  const NON_CONTENT_NODE_SELECTORS = [
    "script,style,noscript,svg,canvas,iframe,form,template",
    "nav,footer,header,aside",
    "[hidden],[aria-hidden='true'],input[type='hidden']",
    "[style*='display:none'],[style*='display: none'],[style*='visibility:hidden'],[style*='visibility: hidden']",
    "[class*='dummy'],[class*='placeholder'],[class*='skeleton'],[class*='loading'],[class*='pager'],[class*='controller'],[class*='dotList'],[class*='dots']"
  ];
  const META_DESCRIPTION_SELECTORS = [
    "meta[name='description']",
    "meta[property='og:description']",
    "meta[name='twitter:description']"
  ];
  const EN_STOPWORDS = new Set([
    "a", "an", "and", "are", "as", "at", "be", "by", "for", "from", "has", "have",
    "in", "is", "it", "its", "of", "on", "or", "that", "the", "to", "was", "were",
    "will", "with", "this", "these", "those", "you", "your", "we", "our", "can",
    "not", "if", "then", "than", "about", "into", "which", "what", "when", "where"
  ]);
  const AI_DISCLOSURE_PATTERNS = [
    /\bai-generated\b/i,
    /\bgenerated by ai\b/i,
    /\bmachine-generated\b/i,
    /\bmachine generated\b/i,
    /\bwritten with (?:gpt|ai)\b/i,
    /\bcreated with (?:gpt|ai)\b/i,
    /\bgenerated with (?:ai|gpt|a neural network|neural network|neural net)\b/i,
    /\bthis (?:story|text|article|post|content) was generated\b/i,
    /\babove text is machine-generated\b/i,
    /\bfree ai-generated (?:novel|story|book)\b/i,
    /\bai novel writing technology\b/i,
    /ai生成/i,
    /aiで生成/i,
    /生成ai/i,
    /aiが作成/i,
    /aiで作成/i
  ];
  const AI_ROUTE_HINT_PATTERNS = [
    /\/story(?:\/|$)/i,
    /\/stories(?:\/|$)/i,
    /\/novel(?:\/|$)/i,
    /\/novels(?:\/|$)/i,
    /\/fiction(?:\/|$)/i,
    /\/generated(?:\/|$)/i,
    /\/prompt(?:\/|$)/i,
    /\bai (?:book|novel|story|fiction)\b/i,
    /\bmachine-generated\b/i
  ];
  const OFFICIAL_GUARD_PATTERNS = [
    /(^|[/.])docs[/.]/i,
    /\/docs?(?:\/|$)/i,
    /\/support(?:\/|$)/i,
    /\/help(?:\/|$)/i,
    /\/pricing(?:\/|$)/i,
    /\/product(?:s)?(?:\/|$)/i,
    /\/feature(?:\/|$)/i,
    /\/spec(?:s)?(?:\/|$)/i,
    /\/shop(?:\/|$)/i,
    /\/store(?:\/|$)/i,
    /apple\.com/i,
    /google\./i,
    /anthropic\.com/i,
    /openai\.com/i,
    /vercel\.com/i,
    /pokemon\.co\.jp/i,
    /pokemoncenter-online\.com/i
  ];

  const DEFAULT_SETTINGS = {
    enabled: true,
    cacheTTLHours: DEFAULT_CACHE_TTL_HOURS
  };

  const HASH_MODEL_DEFAULT = resolveHashModel(globalThis.AI_SCREENER_HASH_MODEL);
  const HASH_MODEL_JA = globalThis.AI_SCREENER_HASH_MODEL_JA
    ? resolveHashModel(globalThis.AI_SCREENER_HASH_MODEL_JA)
    : null;

  const analysisLimiter = createLimiter(ANALYSIS_CONCURRENCY);
  const pendingByUrl = new Map();

  let prefersDarkQuery = null;
  let settings = DEFAULT_SETTINGS;
  let observer = null;
  let scanTimer = null;

  init().catch((error) => {
    console.error("[ai-screener] initialization failed", error);
  });

  async function init() {
    if (!isGoogleSearchPage()) {
      return;
    }

    setupThemeWatcher();
    applyThemeMode();
    injectStyles();

    settings = await getSettings();
    await cleanupExpiredCache(settings.cacheTTLHours);

    chrome.storage.onChanged.addListener((changes, areaName) => {
      if (areaName !== "local" || !changes[SETTINGS_KEY]) {
        return;
      }

      settings = mergeSettings(changes[SETTINGS_KEY].newValue || {});
      if (!settings.enabled) {
        clearResultCards();
        return;
      }
      scanGoogleResults();
    });

    if (!settings.enabled) {
      clearResultCards();
      return;
    }

    startGoogleSearchMode();
  }

  function resolveHashModel(rawModel) {
    const fallback = {
      name: "fallback",
      type: "naive_bayes_hash3",
      dim: 4096,
      max_chars: 1200,
      prior_logit: 0,
      delta: new Array(4096).fill(0),
      calibration: null,
      thresholds: {
        human_max: 0.45,
        ai_min: 0.55
      }
    };

    if (!rawModel || typeof rawModel !== "object") {
      return fallback;
    }

    const dim = Math.max(1, Number(rawModel.dim) || fallback.dim);
    const maxChars = Math.max(200, Number(rawModel.max_chars) || fallback.max_chars);
    const priorLogit = Number(rawModel.prior_logit) || 0;

    let delta = Array.isArray(rawModel.delta) ? rawModel.delta.slice(0, dim) : [];
    if (delta.length < dim) {
      delta = delta.concat(new Array(dim - delta.length).fill(0));
    }

    const humanMax = clamp(Number(rawModel.thresholds?.human_max) || fallback.thresholds.human_max, 0, 1);
    const aiMin = clamp(Number(rawModel.thresholds?.ai_min) || fallback.thresholds.ai_min, 0, 1);

    return {
      name: String(rawModel.name || "hash_nb_char3"),
      type: String(rawModel.type || "naive_bayes_hash3"),
      dim,
      max_chars: maxChars,
      prior_logit: priorLogit,
      delta,
      calibration: resolveCalibrationModel(rawModel.calibration),
      thresholds: {
        human_max: Math.min(humanMax, aiMin),
        ai_min: Math.max(aiMin, humanMax)
      }
    };
  }

  function resolveCalibrationModel(rawCalibration) {
    if (!rawCalibration || typeof rawCalibration !== "object") {
      return null;
    }

    const weights = Array.isArray(rawCalibration.weights) ? rawCalibration.weights.map((value) => Number(value) || 0) : [];
    const means = Array.isArray(rawCalibration.means) ? rawCalibration.means.map((value) => Number(value) || 0) : [];
    const scales = Array.isArray(rawCalibration.scales) ? rawCalibration.scales.map((value) => Number(value) || 1) : [];
    if (weights.length === 0 || weights.length !== means.length || weights.length !== scales.length) {
      return null;
    }

    return {
      bias: Number(rawCalibration.bias) || 0,
      weights,
      means,
      scales
    };
  }

  function isGoogleSearchPage() {
    const host = location.hostname.toLowerCase();
    return host.includes("google.") && location.pathname === "/search";
  }

  function startGoogleSearchMode() {
    applyThemeMode();
    scanGoogleResults();

    observer = new MutationObserver(scheduleSearchScan);
    observer.observe(document.body, {
      childList: true,
      subtree: true
    });

    window.addEventListener("resize", handleWindowResize);
  }

  function scheduleSearchScan() {
    if (scanTimer) {
      clearTimeout(scanTimer);
    }

    scanTimer = setTimeout(() => {
      applyThemeMode();
      scanGoogleResults();
    }, SEARCH_SCAN_DEBOUNCE_MS);
  }

  function handleWindowResize() {
    applyThemeMode();
    for (const card of document.querySelectorAll(`.${CARD_CLASS}`)) {
      applyResultCardLayout(card);
    }
  }

  function clearResultCards() {
    for (const card of document.querySelectorAll(`.${CARD_CLASS}`)) {
      card.remove();
    }
  }

  function scanGoogleResults() {
    if (!settings.enabled) {
      clearResultCards();
      return;
    }

    const results = collectGoogleResults();
    for (const result of results) {
      const card = ensureResultCard(result.container);
      if (isCompletedCardForUrl(card, result.url)) {
        continue;
      }

      setCardLoadingState(card, result.url);

      analyzeResult(result)
        .then((record) => {
          if (!isCardForUrl(card, result.url)) {
            return;
          }

          card.dataset.state = CARD_STATE_DONE;
          renderResultCard(card, record);
        })
        .catch((error) => {
          console.warn("[ai-screener] result analysis failed", error);
          if (!isCardForUrl(card, result.url)) {
            return;
          }

          card.dataset.state = CARD_STATE_ERROR;
          renderResultCardError(card);
        });
    }
  }

  function isCompletedCardForUrl(card, url) {
    return card.dataset.url === url && card.dataset.state === CARD_STATE_DONE;
  }

  function isCardForUrl(card, url) {
    return card.dataset.url === url;
  }

  function setCardLoadingState(card, url) {
    card.dataset.url = url;
    card.dataset.state = CARD_STATE_LOADING;
    renderResultCardChecking(card);
  }

  function collectGoogleResults() {
    const h3Nodes = document.querySelectorAll(RESULT_H3_SELECTOR);
    const seenContainers = new Set();
    const results = [];

    for (const h3 of h3Nodes) {
      const result = buildResultFromHeading(h3, seenContainers);
      if (result) {
        results.push(result);
      }
    }

    return results;
  }

  function buildResultFromHeading(h3, seenContainers) {
    const anchor = h3.closest("a[href]");
    if (!anchor) {
      return null;
    }

    const url = normalizeResultUrl(anchor.href);
    if (!/^https?:\/\//i.test(url)) {
      return null;
    }

    const container = anchor.closest(RESULT_CONTAINER_SELECTOR);
    if (!container || seenContainers.has(container)) {
      return null;
    }

    seenContainers.add(container);

    const snippetNode = container.querySelector(RESULT_SNIPPET_SELECTOR);
    const snippet = normalizeText(snippetNode ? snippetNode.innerText : "");
    const title = normalizeText(h3.innerText || "");

    return {
      container,
      url,
      title,
      snippet
    };
  }

  async function analyzeResult(result) {
    const memoized = pendingByUrl.get(result.url);
    if (memoized) {
      return memoized;
    }

    const task = analysisLimiter(async () => {
      const cacheKey = makeCacheKey(result.url);
      const cached = await getValidCache(cacheKey);
      if (cached) {
        return cached;
      }

      const payload = await resolvePayloadForResult(result);
      const record = createAnalysisRecord(payload);
      await setToStorage({ [cacheKey]: record });
      return record;
    });

    pendingByUrl.set(result.url, task);
    try {
      return await task;
    } finally {
      pendingByUrl.delete(result.url);
    }
  }

  async function resolvePayloadForResult(result) {
    const fetched = await fetchAndExtractPayload(result.url);
    const descriptionPayload = buildPayloadFromMetaDescription(result, fetched);
    const snippetPayload = buildPayloadFromSnippet(result);
    return chooseBestPayload(fetched, descriptionPayload, snippetPayload);
  }

  function createAnalysisRecord(payload) {
    const analyzed = analyzePayload(payload);
    return {
      ...analyzed,
      contentHash: hashString(payload.text || ""),
      cacheVersion: CACHE_VERSION,
      updatedAt: Date.now(),
      source: payload.source || "snippet"
    };
  }

  async function getValidCache(cacheKey) {
    const cacheMap = await getFromStorage(cacheKey);
    const cached = cacheMap ? cacheMap[cacheKey] : null;
    if (
      !cached ||
      Number(cached.cacheVersion) !== CACHE_VERSION ||
      isExpired(cached.updatedAt, settings.cacheTTLHours)
    ) {
      return null;
    }
    return cached;
  }

  async function fetchAndExtractPayload(url) {
    const fetchUrl = resolveFetchUrl(url);
    if (!fetchUrl) {
      return createEmptyPayload("body");
    }

    try {
      const response = await sendMessage({
        type: "FETCH_HTML",
        url: fetchUrl
      });
      if (!response || !response.ok || !response.html) {
        return createEmptyPayload("body");
      }
      return extractFromHtml(response.html, response.finalUrl || fetchUrl);
    } catch (error) {
      console.debug("[ai-screener] fetch fallback to snippet", error);
      return createEmptyPayload("body");
    }
  }

  function resolveFetchUrl(rawUrl) {
    let parsed = null;
    try {
      parsed = new URL(rawUrl);
    } catch (_error) {
      return "";
    }

    if (parsed.protocol === FETCH_SUPPORTED_PROTOCOL) {
      return parsed.href;
    }

    // Keep review-friendly HTTPS-only permissions while still trying the common HTTP->HTTPS upgrade path.
    if (parsed.protocol === FETCH_UPGRADE_PROTOCOL) {
      parsed.protocol = FETCH_SUPPORTED_PROTOCOL;
      return parsed.href;
    }

    return "";
  }

  function buildPayloadFromSnippet(result) {
    const text = normalizeText(`${result.title || ""}\n${result.snippet || ""}`);
    const headingsText = result.title || "";
    const metrics = buildTextMetrics(text, headingsText, 0, "snippet", result.url);
    return {
      text,
      headingsText,
      metaDescription: "",
      externalLinkCount: 0,
      source: "snippet",
      url: result.url,
      qualityScore: metrics.qualityScore,
      metrics
    };
  }

  function buildPayloadFromMetaDescription(result, payload) {
    const description = normalizeText(payload.metaDescription || "");
    if (description.length < MIN_META_DESCRIPTION_LENGTH) {
      return null;
    }

    const heading = normalizeText(payload.headingsText || result.title || "");
    const text = heading && !description.startsWith(heading)
      ? normalizeText(`${heading}\n${description}`)
      : description;
    const externalLinkCount = Number(payload.externalLinkCount) || 0;
    const metrics = buildTextMetrics(text, heading, externalLinkCount, "meta", payload.url || result.url);

    return {
      text,
      headingsText: heading,
      metaDescription: description,
      externalLinkCount,
      source: "meta",
      url: payload.url || result.url,
      qualityScore: metrics.qualityScore,
      metrics
    };
  }

  function chooseBestPayload(fetchedPayload, metaPayload, snippetPayload) {
    const candidates = [fetchedPayload, metaPayload, snippetPayload].filter((payload) => payload && payload.text);
    if (candidates.length === 0) {
      return snippetPayload;
    }

    if (shouldPreferMetaPayload(fetchedPayload, metaPayload)) {
      return finalizeSelectedPayload(metaPayload, fetchedPayload, metaPayload);
    }

    if (
      fetchedPayload &&
      fetchedPayload.text &&
      fetchedPayload.text.length >= MIN_ANALYZABLE_TEXT_LENGTH &&
      Number(fetchedPayload.qualityScore) >= 0.55
    ) {
      return finalizeSelectedPayload(fetchedPayload, fetchedPayload, metaPayload);
    }

    candidates.sort((left, right) => {
      const qualityDiff = (Number(right.qualityScore) || 0) - (Number(left.qualityScore) || 0);
      if (Math.abs(qualityDiff) > 0.0001) {
        return qualityDiff;
      }
      return (right.text || "").length - (left.text || "").length;
    });
    return finalizeSelectedPayload(candidates[0], fetchedPayload, metaPayload);
  }

  function finalizeSelectedPayload(selectedPayload, bodyPayload, metaPayload) {
    if (!selectedPayload) {
      return bodyPayload || metaPayload;
    }

    const metrics = { ...(selectedPayload.metrics || {}) };
    const bodyQuality = Number(bodyPayload?.qualityScore) || 0;
    const metaQuality = Number(metaPayload?.qualityScore) || 0;
    const pageUrl = selectedPayload.url || bodyPayload?.url || metaPayload?.url || "";

    metrics.metaBodyGap = clamp(metaQuality - bodyQuality, -1, 1);
    metrics.shellPageRatio = Math.max(
      Number(metrics.shellPageRatio) || 0,
      computeShellPageRatio(bodyPayload?.metrics || metrics)
    );
    metrics.explicitAiDisclosure = hasExplicitAiDisclosure(
      selectedPayload.headingsText,
      selectedPayload.metaDescription,
      selectedPayload.text,
      pageUrl
    ) ? 1 : 0;
    metrics.aiRouteHint = hasAiRouteHint(pageUrl, selectedPayload.headingsText) ? 1 : 0;
    metrics.officialGuard = looksOfficialGuarded(pageUrl) && metrics.explicitAiDisclosure < 0.5 ? 1 : 0;

    return {
      ...selectedPayload,
      url: pageUrl,
      metrics
    };
  }

  function shouldPreferMetaPayload(fetchedPayload, metaPayload) {
    if (!metaPayload || !metaPayload.text) {
      return false;
    }
    if (!fetchedPayload || !fetchedPayload.text) {
      return true;
    }

    const metrics = fetchedPayload.metrics || {};
    const textLength = Number(metrics.textLength) || fetchedPayload.text.length;
    const sentenceCount = Number(metrics.sentenceCount) || 0;
    const shortLineRatio = Number(metrics.shortLineRatio) || 0;
    const punctuationRatio = Number(metrics.punctuationCharRatio) || 0;
    const headingRatio = Number(metrics.headingBodyRatio) || 0;
    const metaMargin = (Number(metaPayload.qualityScore) || 0) - (Number(fetchedPayload.qualityScore) || 0);
    const metaHasExplicitAiCue = Number(metaPayload.metrics?.explicitAiDisclosure) >= 0.5;

    const bodyLooksLikeUi = (
      shortLineRatio >= 0.48 &&
      sentenceCount <= 4 &&
      punctuationRatio <= 0.025 &&
      textLength <= 420
    );
    const bodyIsTitleHeavy = headingRatio >= 0.28 && textLength <= 480;
    return (
      ((bodyLooksLikeUi || bodyIsTitleHeavy) && metaMargin >= -0.05) ||
      (metaHasExplicitAiCue && (bodyLooksLikeUi || Number(fetchedPayload.qualityScore) < 0.58))
    );
  }

  function normalizeResultUrl(href) {
    try {
      const parsed = new URL(href, location.href);
      const isGoogleRedirect = parsed.hostname.includes("google.") && parsed.pathname === "/url";
      if (isGoogleRedirect) {
        const target = parsed.searchParams.get("url") || parsed.searchParams.get("q");
        if (target && /^https?:\/\//i.test(target)) {
          return target;
        }
      }
      return parsed.href;
    } catch (_error) {
      return href;
    }
  }

  function analyzePayload(payload) {
    const selectedModel = selectHashModel(payload.text || payload.headingsText || "");
    const baseHashScore = computeHashScore(payload.text || "", selectedModel);
    const score = computeFinalScore(payload, selectedModel, baseHashScore);
    const judge = toJudge(score, selectedModel);

    return {
      score,
      judge,
      displayScore: score.toFixed(2)
    };
  }

  function selectHashModel(text) {
    if (HASH_MODEL_JA && isLikelyJapaneseText(text)) {
      return HASH_MODEL_JA;
    }
    return HASH_MODEL_DEFAULT;
  }

  function isLikelyJapaneseText(text) {
    const sample = String(text || "").slice(0, 2400);
    if (!sample) {
      return false;
    }

    const matches = sample.match(/[\u3040-\u30ff\u4e00-\u9fff]/g);
    const jpCount = matches ? matches.length : 0;
    if (jpCount >= 40) {
      return true;
    }
    return jpCount >= 8 && jpCount / Math.max(1, sample.length) >= 0.03;
  }

  function computeHashScore(text, model) {
    const activeModel = model || HASH_MODEL_DEFAULT;
    const normalized = normalizeHashText(text);
    if (normalized.length < 3) {
      return 0.5;
    }

    const limit = Math.min(normalized.length, activeModel.max_chars);
    let logit = activeModel.prior_logit;

    for (let i = 0; i < limit - 2; i += 1) {
      const bin = hashTrigram(normalized, i, activeModel.dim);
      logit += activeModel.delta[bin] || 0;
    }

    return sigmoid(logit);
  }

  function computeFinalScore(payload, model, baseHashScore) {
    const calibration = model && model.calibration;
    const metrics = payload.metrics || buildTextMetrics(
      payload.text || "",
      payload.headingsText || "",
      Number(payload.externalLinkCount) || 0,
      payload.source || "body",
      payload.url || ""
    );

    if (!calibration) {
      return blendScoreWithQuality(baseHashScore, metrics.qualityScore, metrics);
    }

    const vector = createFeatureVector(baseHashScore, metrics);
    let logit = Number(calibration.bias) || 0;
    for (let index = 0; index < vector.length; index += 1) {
      const mean = Number(calibration.means[index]) || 0;
      const scale = Math.abs(Number(calibration.scales[index]) || 1) > 1e-9
        ? Number(calibration.scales[index]) || 1
        : 1;
      const weight = Number(calibration.weights[index]) || 0;
      logit += ((vector[index] - mean) / scale) * weight;
    }

    return blendScoreWithQuality(sigmoid(logit), metrics.qualityScore, metrics);
  }

  function blendScoreWithQuality(score, qualityScore, metrics) {
    const sourcePenalty = 0.10 * Number(metrics?.sourceSnippet || 0) + 0.04 * Number(metrics?.sourceMeta || 0);
    const confidence = clamp((Number(qualityScore) || 0) - sourcePenalty, 0, 1);
    const blend = 0.25 + 0.75 * confidence;
    return clamp(0.5 + (Number(score) - 0.5) * blend, 0, 1);
  }

  function createFeatureVector(baseHashScore, metrics) {
    return [
      clamp(baseHashScore, 0, 1),
      Math.log1p(Math.max(0, Number(metrics.textLength) || 0)),
      Number(metrics.sentenceCount) || 0,
      Number(metrics.avgSentenceLength) || 0,
      Number(metrics.sentenceLengthStd) || 0,
      Number(metrics.lineCount) || 0,
      Number(metrics.shortLineRatio) || 0,
      Number(metrics.repeatLineRatio) || 0,
      Number(metrics.uniqueLineRatio) || 0,
      Number(metrics.bulletLineRatio) || 0,
      Number(metrics.headingBodyRatio) || 0,
      Number(metrics.numericCharRatio) || 0,
      Number(metrics.dateLikeRatio) || 0,
      Number(metrics.currencyLikeRatio) || 0,
      Number(metrics.productCodeRatio) || 0,
      Number(metrics.externalLinkDensity) || 0,
      Number(metrics.punctuationCharRatio) || 0,
      Number(metrics.symbolCharRatio) || 0,
      Number(metrics.qualityScore) || 0,
      Number(metrics.explicitAiDisclosure) || 0,
      Number(metrics.aiRouteHint) || 0,
      Number(metrics.shellPageRatio) || 0,
      Number(metrics.officialGuard) || 0,
      Number(metrics.metaBodyGap) || 0,
      Number(metrics.sourceBody) || 0,
      Number(metrics.sourceMeta) || 0,
      Number(metrics.sourceSnippet) || 0,
      Number(metrics.jpCharRatio) || 0,
      Number(metrics.hiraganaRatio) || 0,
      Number(metrics.katakanaRatio) || 0,
      Number(metrics.kanjiRatio) || 0,
      Number(metrics.latinRatio) || 0,
      Number(metrics.stopwordRatio) || 0,
      Number(metrics.vocabRichness) || 0
    ];
  }

  function normalizeHashText(value) {
    return normalizeText(value || "")
      .toLowerCase()
      .replace(/\u00a0/g, " ");
  }

  function hashTrigram(text, start, dim) {
    let h = 2166136261;
    for (let i = 0; i < 3; i += 1) {
      h ^= text.charCodeAt(start + i);
      h = Math.imul(h, 16777619) >>> 0;
    }
    return h % dim;
  }

  function toJudge(score, model) {
    const activeModel = model || HASH_MODEL_DEFAULT;
    if (score < activeModel.thresholds.human_max) {
      return "Human";
    }
    if (score < activeModel.thresholds.ai_min) {
      return "Unknown";
    }
    return "AI";
  }

  function sigmoid(value) {
    const x = Number(value) || 0;
    if (x >= 0) {
      const z = Math.exp(-x);
      return 1 / (1 + z);
    }
    const z = Math.exp(x);
    return z / (1 + z);
  }

  function extractFromHtml(html, url) {
    try {
      const sanitized = sanitizeFetchedHtml(html);
      const doc = new DOMParser().parseFromString(sanitized, "text/html");
      return extractFromDocument(doc, url, "body");
    } catch (_error) {
      return createEmptyPayload("body");
    }
  }

  function sanitizeFetchedHtml(html) {
    return String(html || "").replace(/<base\b[^>]*>/gi, "");
  }

  function createEmptyPayload(source) {
    return {
      text: "",
      headingsText: "",
      metaDescription: "",
      externalLinkCount: 0,
      source,
      url: "",
      qualityScore: 0,
      metrics: buildTextMetrics("", "", 0, source || "body", "")
    };
  }

  function extractFromDocument(doc, url, source = "document") {
    const body = doc.body;
    if (!body) {
      return createEmptyPayload(source);
    }

    const clone = body.cloneNode(true);
    pruneNonContentNodes(clone);

    const mainElement = pickMainTextElement(clone);
    const text = postProcessExtractedText(mainElement.innerText || clone.innerText || "");
    const headingsText = Array.from(mainElement.querySelectorAll("h1,h2,h3"))
      .map((node) => normalizeText(node.innerText || ""))
      .filter(Boolean)
      .join(" ");
    const metaDescription = readMetaDescription(doc);
    const externalLinkCount = countExternalLinks(mainElement, url);
    const payloadSource = source === "fetched" ? "body" : source;
    const metrics = buildTextMetrics(text, headingsText, externalLinkCount, payloadSource, url);

    return {
      text,
      headingsText,
      metaDescription,
      externalLinkCount,
      source: payloadSource,
      url,
      qualityScore: metrics.qualityScore,
      metrics
    };
  }

  function pickMainTextElement(root) {
    let best = null;
    let bestLength = 0;

    for (const selector of ARTICLE_CANDIDATE_SELECTORS) {
      for (const element of root.querySelectorAll(selector)) {
        const length = normalizeText(element.innerText || "").length;
        if (length > bestLength) {
          best = element;
          bestLength = length;
        }
      }
    }

    return best || root;
  }

  function pruneNonContentNodes(root) {
    for (const selector of NON_CONTENT_NODE_SELECTORS) {
      removeNodesBySelector(root, selector);
    }
  }

  function removeNodesBySelector(root, selector) {
    for (const node of root.querySelectorAll(selector)) {
      node.remove();
    }
  }

  function postProcessExtractedText(value) {
    const seen = new Map();
    const lines = String(value || "")
      .replace(/\u3000+/g, " ")
      .split(/\n+/)
      .map((line) => normalizeText(line))
      .filter(Boolean)
      .filter((line) => !isUiOnlyLine(line));

    const kept = [];
    for (const line of lines) {
      const count = seen.get(line) || 0;
      if (count >= MAX_IDENTICAL_LINE_REPEATS) {
        continue;
      }
      seen.set(line, count + 1);
      kept.push(line);
    }

    return kept.join("\n");
  }

  function isUiOnlyLine(line) {
    const value = String(line || "").trim();
    if (!value) {
      return true;
    }
    if (/^(前へ|次へ|prev|next|\d+)$/i.test(value)) {
      return true;
    }
    if (/^[\p{P}\p{S}ー・]+$/u.test(value)) {
      return true;
    }
    if (/^[A-Z0-9\-_.]{1,6}$/u.test(value)) {
      return true;
    }
    return value.length < 4 && !/[。！？!?.]/.test(value);
  }

  function buildTextMetrics(text, headingsText = "", externalLinkCount = 0, source = "body", pageUrl = "", metaQualityScore = 0, bodyQualityScore = 0) {
    const normalizedText = normalizeText(text || "");
    const lines = normalizedText
      .split(/\n+/)
      .map((line) => normalizeText(line))
      .filter(Boolean)
      .filter((line) => !isUiOnlyLine(line));
    const uniqueLineRatio = lines.length === 0 ? 0 : new Set(lines).size / lines.length;
    const repeatLineRatio = lines.length === 0 ? 0 : 1 - uniqueLineRatio;
    const shortLineCount = lines.filter((line) => line.length <= 24).length;
    const bulletLineCount = lines.filter((line) => /^(?:[-*•・]|[0-9]{1,2}[.)]|[0-9]{1,2}[:：])/.test(line)).length;
    const sentences = splitSentences(normalizedText);
    const sentenceLengths = sentences.map((sentence) => sentence.length);
    const tokens = tokenizeWords(normalizedText);
    const stopwordCount = tokens.filter((token) => EN_STOPWORDS.has(token)).length;

    const metrics = {
      textLength: normalizedText.length,
      sentenceCount: sentences.length,
      avgSentenceLength: average(sentenceLengths),
      sentenceLengthStd: standardDeviation(sentenceLengths),
      lineCount: lines.length,
      shortLineRatio: ratio(shortLineCount, lines.length),
      repeatLineRatio,
      uniqueLineRatio,
      bulletLineRatio: ratio(bulletLineCount, lines.length),
      headingBodyRatio: Math.min(2, (normalizeText(headingsText || "").length) / Math.max(1, normalizedText.length)),
      numericCharRatio: matchRatio(normalizedText, /\d/g),
      dateLikeRatio: ratio((normalizedText.match(/(?:\d{4}[/-]\d{1,2}[/-]\d{1,2}|\d{1,2}月\d{1,2}日|\d{1,2}\/\d{1,2})/g) || []).length, Math.max(1, sentences.length)),
      currencyLikeRatio: ratio((normalizedText.match(/(?:¥|\$|€|£|円|USD|JPY)/g) || []).length, Math.max(1, sentences.length)),
      productCodeRatio: ratio((normalizedText.match(/\b[A-Z0-9][A-Z0-9._-]{3,}\b/g) || []).length, Math.max(1, tokens.length)),
      externalLinkDensity: ratio(externalLinkCount, Math.max(1, lines.length)),
      punctuationCharRatio: matchRatio(normalizedText, /[。．！？!?.,;:：；、]/g),
      symbolCharRatio: matchRatio(normalizedText, /[\-–—_/\\|+=*&^%$#@~`"'(){}\[\]<>]/g),
      sourceBody: source === "body" ? 1 : 0,
      sourceMeta: source === "meta" ? 1 : 0,
      sourceSnippet: source === "snippet" ? 1 : 0,
      jpCharRatio: matchRatio(normalizedText, /[\u3040-\u30ff\u4e00-\u9fff]/g),
      hiraganaRatio: matchRatio(normalizedText, /[\u3040-\u309f]/g),
      katakanaRatio: matchRatio(normalizedText, /[\u30a0-\u30ff]/g),
      kanjiRatio: matchRatio(normalizedText, /[\u4e00-\u9fff]/g),
      latinRatio: matchRatio(normalizedText, /[A-Za-z]/g),
      stopwordRatio: isLikelyJapaneseText(normalizedText) ? 0 : ratio(stopwordCount, Math.max(1, tokens.length)),
      vocabRichness: ratio(new Set(tokens).size, Math.max(1, tokens.length))
    };

    metrics.qualityScore = computeQualityScore(metrics, source);
    metrics.explicitAiDisclosure = hasExplicitAiDisclosure(headingsText, normalizedText) ? 1 : 0;
    metrics.aiRouteHint = hasAiRouteHint(pageUrl, headingsText) ? 1 : 0;
    metrics.shellPageRatio = computeShellPageRatio(metrics);
    metrics.officialGuard = looksOfficialGuarded(pageUrl) && metrics.explicitAiDisclosure < 0.5 ? 1 : 0;
    metrics.metaBodyGap = clamp(Number(metaQualityScore) - Number(bodyQualityScore), -1, 1);
    return metrics;
  }

  function computeQualityScore(metrics, source) {
    const sentenceSignal = metrics.sentenceCount >= 2 ? 1 : metrics.sentenceCount / 2;
    const contentSignal = Math.min(1, (Number(metrics.textLength) || 0) / 900);
    const sourceBonus = source === "body" ? 0.15 : (source === "meta" ? 0.05 : -0.05);
    const quality = (
      0.28 * contentSignal +
      0.18 * sentenceSignal +
      0.18 * (Number(metrics.uniqueLineRatio) || 0) +
      0.14 * (1 - (Number(metrics.shortLineRatio) || 0)) +
      0.12 * (1 - (Number(metrics.repeatLineRatio) || 0)) +
      0.10 * Math.max(0, 1 - (Number(metrics.bulletLineRatio) || 0)) +
      sourceBonus
    );
    return clamp(quality, 0, 1);
  }

  function splitSentences(text) {
    const normalized = normalizeText(text || "");
    if (!normalized) {
      return [];
    }
    const parts = normalized
      .split(/(?:[。！？!?]+|\.\s+)/)
      .map((value) => normalizeText(value))
      .filter(Boolean);
    return parts.length > 0 ? parts : [normalized];
  }

  function tokenizeWords(text) {
    return Array.from(String(text || "").matchAll(/[A-Za-z']+/g), (match) => String(match[0] || "").toLowerCase());
  }

  function matchRatio(text, pattern) {
    if (!text) {
      return 0;
    }
    const matches = text.match(pattern);
    return ratio(matches ? matches.length : 0, text.length);
  }

  function average(values) {
    if (!Array.isArray(values) || values.length === 0) {
      return 0;
    }
    return values.reduce((sum, value) => sum + (Number(value) || 0), 0) / values.length;
  }

  function hasExplicitAiDisclosure(...values) {
    const combined = values
      .map((value) => normalizeText(value || ""))
      .filter(Boolean)
      .join("\n");
    if (!combined) {
      return false;
    }
    return AI_DISCLOSURE_PATTERNS.some((pattern) => pattern.test(combined));
  }

  function hasAiRouteHint(pageUrl, headingsText = "") {
    const combined = [normalizeText(pageUrl || ""), normalizeText(headingsText || "")]
      .filter(Boolean)
      .join("\n");
    if (!combined) {
      return false;
    }
    return AI_ROUTE_HINT_PATTERNS.some((pattern) => pattern.test(combined));
  }

  function looksOfficialGuarded(pageUrl) {
    const value = normalizeText(pageUrl || "");
    if (!value) {
      return false;
    }
    return OFFICIAL_GUARD_PATTERNS.some((pattern) => pattern.test(value));
  }

  function computeShellPageRatio(metrics) {
    const shortLineRatio = Number(metrics.shortLineRatio) || 0;
    const repeatLineRatio = Number(metrics.repeatLineRatio) || 0;
    const headingRatio = Number(metrics.headingBodyRatio) || 0;
    const sentenceCount = Number(metrics.sentenceCount) || 0;
    const punctuationRatio = Number(metrics.punctuationCharRatio) || 0;
    const textLength = Number(metrics.textLength) || 0;

    const sentencePenalty = clamp((4 - Math.min(sentenceCount, 4)) / 4, 0, 1);
    const punctuationPenalty = clamp((0.03 - Math.min(punctuationRatio, 0.03)) / 0.03, 0, 1);
    const lengthPenalty = clamp((480 - Math.min(textLength, 480)) / 480, 0, 1);
    return clamp(
      0.28 * shortLineRatio +
      0.24 * repeatLineRatio +
      0.22 * clamp(headingRatio / 0.4, 0, 1) +
      0.14 * sentencePenalty +
      0.07 * punctuationPenalty +
      0.05 * lengthPenalty,
      0,
      1
    );
  }

  function standardDeviation(values) {
    if (!Array.isArray(values) || values.length < 2) {
      return 0;
    }
    const mean = average(values);
    const variance = values.reduce((sum, value) => {
      const delta = (Number(value) || 0) - mean;
      return sum + delta * delta;
    }, 0) / values.length;
    return Math.sqrt(variance);
  }

  function ratio(part, whole) {
    const denominator = Number(whole) || 0;
    if (denominator <= 0) {
      return 0;
    }
    return (Number(part) || 0) / denominator;
  }

  function readMetaDescription(doc) {
    for (const selector of META_DESCRIPTION_SELECTORS) {
      const content = normalizeText(doc.querySelector(selector)?.getAttribute("content") || "");
      if (content) {
        return content;
      }
    }

    return "";
  }

  function countExternalLinks(root, pageUrl) {
    let host = "";
    try {
      host = new URL(pageUrl).host;
    } catch (_error) {
      host = "";
    }

    let count = 0;
    for (const anchor of root.querySelectorAll("a[href]")) {
      const href = anchor.getAttribute("href");
      if (!href || !/^https?:\/\//i.test(href)) {
        continue;
      }

      try {
        const linked = new URL(href);
        if (!host || linked.host !== host) {
          count += 1;
        }
      } catch (_error) {
        continue;
      }
    }

    return count;
  }

  function ensureResultCard(container) {
    let card = container.querySelector(`.${CARD_CLASS}`);
    if (!card) {
      card = document.createElement("div");
      card.className = `${CARD_CLASS} ai-screener-card-checking`;
      container.prepend(card);
    }

    const computed = window.getComputedStyle(container);
    if (computed.position === "static") {
      container.style.position = "relative";
    }

    applyResultCardLayout(card);
    return card;
  }

  function applyResultCardLayout(card) {
    if (window.innerWidth < INLINE_CARD_BREAKPOINT) {
      card.classList.add("ai-screener-card-inline");
      return;
    }
    card.classList.remove("ai-screener-card-inline");
  }

  function renderResultCardChecking(card) {
    setResultCardTone(card, "checking");
    card.innerHTML = createResultCardMarkup("--", "Checking");
    card.title = "判定中";
  }

  function renderResultCard(card, record) {
    const tone = judgeToTone(record.judge);
    setResultCardTone(card, tone);
    card.innerHTML = createResultCardMarkup(record.displayScore, record.judge);
    card.title = `Score: ${record.displayScore} / Judge: ${record.judge}`;
  }

  function renderResultCardError(card) {
    setResultCardTone(card, "error");
    card.innerHTML = createResultCardMarkup("--", "N/A");
    card.title = "Score: -- / Judge: N/A";
  }

  function setResultCardTone(card, tone) {
    card.classList.remove(...CARD_TONE_CLASSES);
    card.classList.add(`ai-screener-card-${tone}`);
  }

  function judgeToTone(judge) {
    if (judge === "AI") {
      return "ai";
    }
    if (judge === "Human") {
      return "human";
    }
    return "unknown";
  }

  function createResultCardMarkup(displayScore, judge) {
    return `
      <div class="ai-screener-mini-row">
        <span class="ai-screener-mini-k">Score</span>
        <strong class="ai-screener-mini-v">${escapeHtml(displayScore)}</strong>
      </div>
      <div class="ai-screener-mini-row">
        <span class="ai-screener-mini-k">Judge</span>
        <strong class="ai-screener-mini-v ai-screener-mini-judge">${escapeHtml(judge)}</strong>
      </div>
    `;
  }

  async function cleanupExpiredCache(ttlHours) {
    const all = await getFromStorage(null);
    const now = Date.now();
    const ttlMs = getCacheTtlMs(ttlHours);
    const keysToDelete = [];

    for (const [key, value] of Object.entries(all || {})) {
      if (!key.startsWith(CACHE_PREFIX) || !value || typeof value !== "object") {
        continue;
      }

      const updatedAt = Number(value.updatedAt) || 0;
      if (!updatedAt || now - updatedAt > ttlMs) {
        keysToDelete.push(key);
      }
    }

    if (keysToDelete.length > 0) {
      await removeFromStorage(keysToDelete);
    }
  }

  function isExpired(updatedAt, ttlHours) {
    if (!updatedAt) {
      return true;
    }
    return Date.now() - Number(updatedAt) > getCacheTtlMs(ttlHours);
  }

  function getCacheTtlMs(ttlHours) {
    const hours = Math.max(1, Number(ttlHours) || DEFAULT_CACHE_TTL_HOURS);
    return hours * 60 * 60 * 1000;
  }

  function makeCacheKey(url) {
    return `${CACHE_PREFIX}${hashString(url)}`;
  }

  async function getSettings() {
    const result = await getFromStorage(SETTINGS_KEY);
    return mergeSettings(result[SETTINGS_KEY] || {});
  }

  function mergeSettings(raw) {
    const merged = {
      ...DEFAULT_SETTINGS,
      ...(raw || {})
    };

    return {
      enabled: merged.enabled !== false,
      cacheTTLHours: Math.max(1, Number(merged.cacheTTLHours) || DEFAULT_CACHE_TTL_HOURS)
    };
  }

  function injectStyles() {
    if (document.getElementById("ai-screener-style")) {
      return;
    }

    const style = document.createElement("style");
    style.id = "ai-screener-style";
    style.textContent = `
      :root {
        --ais-text: #1a1f2b;
        --ais-muted: #586174;
        --ais-surface: rgba(255, 255, 255, 0.96);
        --ais-border: rgba(38, 49, 66, 0.2);
        --ais-shadow: rgba(14, 20, 29, 0.15);
        --ais-tone-neutral: #6b7688;
        --ais-tone-unknown: #5f739d;
        --ais-tone-human: #1f8f67;
        --ais-tone-ai: #cf405d;
        --ais-tone-error: #c08a3f;
        --ais-judge-unknown: #38507a;
        --ais-judge-human: #166b4d;
        --ais-judge-ai: #9b1f38;
        --ais-judge-error: #8f6226;
      }
      :root.ai-screener-theme-dark {
        --ais-text: #e6edf7;
        --ais-muted: #9ca8bc;
        --ais-surface: rgba(19, 24, 33, 0.95);
        --ais-border: rgba(161, 182, 210, 0.28);
        --ais-shadow: rgba(0, 0, 0, 0.42);
        --ais-tone-neutral: #a3b2c8;
        --ais-tone-unknown: #b4c7ea;
        --ais-tone-human: #5bd1ab;
        --ais-tone-ai: #ff8fa6;
        --ais-tone-error: #f5bc74;
        --ais-judge-unknown: #d3e0fb;
        --ais-judge-human: #a7edd8;
        --ais-judge-ai: #ffc0cd;
        --ais-judge-error: #ffe0b8;
      }
      .ai-screener-card {
        --ais-accent: var(--ais-tone-neutral);
        --ais-judge: var(--ais-muted);
        box-sizing: border-box;
        border: 1px solid var(--ais-border);
        border-left: 3px solid var(--ais-accent);
        border-radius: 8px;
        background: var(--ais-surface);
        color: var(--ais-text);
        font: 600 13px/1.3 -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
        letter-spacing: 0;
        box-shadow: 0 2px 8px var(--ais-shadow);
        pointer-events: none;
        position: absolute;
        left: -138px;
        top: 0;
        width: 128px;
        padding: 8px 9px;
        z-index: 2;
      }
      .ai-screener-mini-row {
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: 8px;
      }
      .ai-screener-mini-row + .ai-screener-mini-row {
        margin-top: 4px;
      }
      .ai-screener-mini-k {
        color: var(--ais-muted);
        font-size: 12px;
      }
      .ai-screener-mini-v {
        font-size: 13px;
        font-weight: 700;
      }
      .ai-screener-mini-judge {
        color: var(--ais-judge);
      }
      .ai-screener-card-checking {
        --ais-accent: var(--ais-tone-neutral);
        --ais-judge: var(--ais-muted);
      }
      .ai-screener-card-human {
        --ais-accent: var(--ais-tone-human);
        --ais-judge: var(--ais-judge-human);
      }
      .ai-screener-card-unknown {
        --ais-accent: var(--ais-tone-unknown);
        --ais-judge: var(--ais-judge-unknown);
      }
      .ai-screener-card-ai {
        --ais-accent: var(--ais-tone-ai);
        --ais-judge: var(--ais-judge-ai);
      }
      .ai-screener-card-error {
        --ais-accent: var(--ais-tone-error);
        --ais-judge: var(--ais-judge-error);
      }
      .ai-screener-card-inline {
        position: static;
        left: auto;
        top: auto;
        width: 128px;
        margin: 0 0 8px;
      }
      @media (max-width: 1179px) {
        .ai-screener-card {
          position: static;
          left: auto;
          top: auto;
          width: 128px;
          margin: 0 0 8px;
        }
      }
    `;

    document.documentElement.appendChild(style);
  }

  function setupThemeWatcher() {
    if (typeof window.matchMedia !== "function") {
      return;
    }

    prefersDarkQuery = window.matchMedia("(prefers-color-scheme: dark)");
    const handler = () => applyThemeMode();

    if (typeof prefersDarkQuery.addEventListener === "function") {
      prefersDarkQuery.addEventListener("change", handler);
      return;
    }
    if (typeof prefersDarkQuery.addListener === "function") {
      prefersDarkQuery.addListener(handler);
    }
  }

  function applyThemeMode() {
    const root = document.documentElement;
    const mode = detectThemeMode();
    root.classList.remove("ai-screener-theme-light", "ai-screener-theme-dark");
    root.classList.add(`ai-screener-theme-${mode}`);
  }

  function detectThemeMode() {
    const bodyBg = readNodeBackgroundColor(document.body);
    const rootBg = readNodeBackgroundColor(document.documentElement);
    const background = bodyBg || rootBg;

    if (background && isDarkColor(background)) {
      return "dark";
    }
    if (prefersDarkQuery && prefersDarkQuery.matches) {
      return "dark";
    }
    return "light";
  }

  function readNodeBackgroundColor(node) {
    if (!node) {
      return "";
    }

    const value = window.getComputedStyle(node).backgroundColor || "";
    if (!value || value === "transparent" || value === "rgba(0, 0, 0, 0)") {
      return "";
    }
    return value;
  }

  function isDarkColor(color) {
    const rgb = parseColorToRgb(color);
    if (!rgb) {
      return false;
    }

    const [r, g, b] = rgb.map((value) => value / 255);
    const luminance = 0.2126 * toLinear(r) + 0.7152 * toLinear(g) + 0.0722 * toLinear(b);
    return luminance < 0.48;
  }

  function parseColorToRgb(color) {
    const rgbMatch = color.match(/rgba?\(\s*([\d.]+)\s*,\s*([\d.]+)\s*,\s*([\d.]+)/i);
    if (rgbMatch) {
      return [
        clamp(Number(rgbMatch[1]) || 0, 0, 255),
        clamp(Number(rgbMatch[2]) || 0, 0, 255),
        clamp(Number(rgbMatch[3]) || 0, 0, 255)
      ];
    }

    const hex = color.trim().replace("#", "");
    if (/^[a-f\d]{3}$/i.test(hex)) {
      return [
        parseInt(hex[0] + hex[0], 16),
        parseInt(hex[1] + hex[1], 16),
        parseInt(hex[2] + hex[2], 16)
      ];
    }
    if (/^[a-f\d]{6}$/i.test(hex)) {
      return [
        parseInt(hex.slice(0, 2), 16),
        parseInt(hex.slice(2, 4), 16),
        parseInt(hex.slice(4, 6), 16)
      ];
    }
    return null;
  }

  function toLinear(channel) {
    if (channel <= 0.03928) {
      return channel / 12.92;
    }
    return ((channel + 0.055) / 1.055) ** 2.4;
  }

  async function sendMessage(message) {
    return callChromeApi((callback) => chrome.runtime.sendMessage(message, callback));
  }

  function getFromStorage(key) {
    return callChromeApi((callback) => chrome.storage.local.get(key, callback));
  }

  function setToStorage(items) {
    return callChromeApi((callback) => {
      chrome.storage.local.set(items, () => callback());
    });
  }

  function removeFromStorage(keys) {
    return callChromeApi((callback) => {
      chrome.storage.local.remove(keys, () => callback());
    });
  }

  function callChromeApi(executor) {
    return new Promise((resolve, reject) => {
      executor((value) => {
        const error = chrome.runtime.lastError;
        if (error) {
          reject(new Error(error.message));
          return;
        }
        resolve(value);
      });
    });
  }

  function createLimiter(limit) {
    let active = 0;
    const queue = [];

    const pump = () => {
      if (active >= limit || queue.length === 0) {
        return;
      }

      const entry = queue.shift();
      active += 1;

      Promise.resolve()
        .then(entry.task)
        .then(entry.resolve, entry.reject)
        .finally(() => {
          active -= 1;
          pump();
        });
    };

    return (task) =>
      new Promise((resolve, reject) => {
        queue.push({ task, resolve, reject });
        pump();
      });
  }

  function normalizeText(value) {
    return String(value || "")
      .replace(/\u00a0/g, " ")
      .replace(/\u3000/g, " ")
      .replace(/[ \t\f\v]+/g, " ")
      .replace(/\n{3,}/g, "\n\n")
      .trim();
  }

  function escapeHtml(value) {
    return String(value || "")
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;")
      .replace(/'/g, "&#39;");
  }

  function clamp(value, min, max) {
    const safeMin = Number.isFinite(min) ? min : 0;
    const safeMax = Number.isFinite(max) ? max : 1;
    const num = Number(value);
    if (!Number.isFinite(num)) {
      return safeMin;
    }
    return Math.min(safeMax, Math.max(safeMin, num));
  }

  function hashString(input) {
    let hash = 5381;
    const str = String(input || "");
    for (let i = 0; i < str.length; i += 1) {
      hash = (hash * 33) ^ str.charCodeAt(i);
    }
    return (hash >>> 0).toString(36);
  }
})();
